### PR TITLE
Add New Rule Builder: Tactic Generator

### PR DESCRIPTION
**Pull request by yangky11**
This PR adds a new rule builder, allowing the user to tag an `MVarID -> MetaM (Array (String × Float))` as a "tactic generator". For example,
```lean
@[aesop unsafe 80% tactic]
def x : MVarId → MetaM (Array (String × Float)) := fun _ => do
  return #[("rw [Nat.add_comm b]", 0.5), ("rw [Nat.add_assoc]", 0.9), ("rw [Nat.add_comm]", 0.8)]
```

Here the scores (0.5, 0.9, 0.8) are "probability modifiers". They are multiplied to the success probabilities during proof search.

Please see the new `AesopTest/TacGen.lean` file for a complete use case.

The user is free to make the tactic generator arbitrarily complex (e.g., using LLMs).

### CODE REVIEW

**Comment by yangky11** [comment]
Hi @JLimperg, thank you for the changes; they look great to me. I'll try to integrate it with LLMs and do more testing. I'll post an update later.

**Comment by yangky11** [comment]
Hi Jannis, I see you're working on the script builder (not in this PR). How far are we from always being able to produce a proof script whenever the `aesop` tactic succeeds? The script builder is important for LLM-aesop to become useful because LLMs may not generate the same set of tactic suggestions every time. It's important for the user to be able to replace the `aesop` tactic with the actual tactics.

**Comment by yangky11** [comment]
I have tested https://github.com/JLimperg/aesop/tree/aesop-llm in the `dev` branch of LeanInfer: https://github.com/lean-dojo/LeanInfer/blob/dev/LeanInferTests/Aesop.lean. It works great! 

I plan to integrate this feature into the next release of LeanInfer, which will probably come out later this month (with some other ongoing improvements).

A minor question: The `100%` [here](https://github.com/lean-dojo/LeanInfer/blob/e766d408bc8b2d4ff1a27d74d5be28a2972b3215/LeanInferTests/Aesop.lean#L12) doesn't really play any role (since the probabilities are produced by the model)? If so, can we get rid of it?

**Comment by JLimperg** [comment]
> How far are we from always being able to produce a proof script whenever the aesop tactic succeeds?

Producing a functioning script is not so difficult and should already work, apart from small bugs. E.g. in `AesopTest.List`, there's only one Aesop call that doesn't produce a functioning script. If you do `set_option aesop.check.script true`, Aesop will check whether the generated script would solve the goal.

What I'm currently working on is making these scripts more idiomatic (no weird tactics, proper structure, etc.). This is, as it turns out, quite annoying.

> I have tested https://github.com/JLimperg/aesop/tree/aesop-llm in the dev branch of LeanInfer: https://github.com/lean-dojo/LeanInfer/blob/dev/LeanInferTests/Aesop.lean. It works great!

Nice, happy to hear! I'll merge this into Aesop master then.

> A minor question: The 100% [here](https://github.com/lean-dojo/LeanInfer/blob/e766d408bc8b2d4ff1a27d74d5be28a2972b3215/LeanInferTests/Aesop.lean#L12) doesn't really play any role (since the probabilities are produced by the model)? If so, can we get rid of it?

I could maybe special-case `TacGen` rules. Will see.

**Comment by JLimperg** [comment]
Closing this PR since the `aesop-llm` changes are now in master.

**Pull request closed without merging**
